// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/sphinx-coininfo/pkg/db/ent/coininfo"
	"github.com/google/uuid"
)

// CoinInfoCreate is the builder for creating a CoinInfo entity.
type CoinInfoCreate struct {
	config
	mutation *CoinInfoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (cic *CoinInfoCreate) SetName(s string) *CoinInfoCreate {
	cic.mutation.SetName(s)
	return cic
}

// SetUnit sets the "unit" field.
func (cic *CoinInfoCreate) SetUnit(s string) *CoinInfoCreate {
	cic.mutation.SetUnit(s)
	return cic
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableUnit(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetUnit(*s)
	}
	return cic
}

// SetReservedAmount sets the "reserved_amount" field.
func (cic *CoinInfoCreate) SetReservedAmount(u uint64) *CoinInfoCreate {
	cic.mutation.SetReservedAmount(u)
	return cic
}

// SetNillableReservedAmount sets the "reserved_amount" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableReservedAmount(u *uint64) *CoinInfoCreate {
	if u != nil {
		cic.SetReservedAmount(*u)
	}
	return cic
}

// SetPreSale sets the "pre_sale" field.
func (cic *CoinInfoCreate) SetPreSale(b bool) *CoinInfoCreate {
	cic.mutation.SetPreSale(b)
	return cic
}

// SetNillablePreSale sets the "pre_sale" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillablePreSale(b *bool) *CoinInfoCreate {
	if b != nil {
		cic.SetPreSale(*b)
	}
	return cic
}

// SetLogo sets the "logo" field.
func (cic *CoinInfoCreate) SetLogo(s string) *CoinInfoCreate {
	cic.mutation.SetLogo(s)
	return cic
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableLogo(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetLogo(*s)
	}
	return cic
}

// SetEnv sets the "env" field.
func (cic *CoinInfoCreate) SetEnv(s string) *CoinInfoCreate {
	cic.mutation.SetEnv(s)
	return cic
}

// SetNillableEnv sets the "env" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableEnv(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetEnv(*s)
	}
	return cic
}

// SetForPay sets the "for_pay" field.
func (cic *CoinInfoCreate) SetForPay(b bool) *CoinInfoCreate {
	cic.mutation.SetForPay(b)
	return cic
}

// SetNillableForPay sets the "for_pay" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableForPay(b *bool) *CoinInfoCreate {
	if b != nil {
		cic.SetForPay(*b)
	}
	return cic
}

// SetHomePage sets the "home_page" field.
func (cic *CoinInfoCreate) SetHomePage(s string) *CoinInfoCreate {
	cic.mutation.SetHomePage(s)
	return cic
}

// SetNillableHomePage sets the "home_page" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableHomePage(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetHomePage(*s)
	}
	return cic
}

// SetSpecs sets the "specs" field.
func (cic *CoinInfoCreate) SetSpecs(s string) *CoinInfoCreate {
	cic.mutation.SetSpecs(s)
	return cic
}

// SetNillableSpecs sets the "specs" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableSpecs(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetSpecs(*s)
	}
	return cic
}

// SetCreatedAt sets the "created_at" field.
func (cic *CoinInfoCreate) SetCreatedAt(u uint32) *CoinInfoCreate {
	cic.mutation.SetCreatedAt(u)
	return cic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableCreatedAt(u *uint32) *CoinInfoCreate {
	if u != nil {
		cic.SetCreatedAt(*u)
	}
	return cic
}

// SetUpdatedAt sets the "updated_at" field.
func (cic *CoinInfoCreate) SetUpdatedAt(u uint32) *CoinInfoCreate {
	cic.mutation.SetUpdatedAt(u)
	return cic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableUpdatedAt(u *uint32) *CoinInfoCreate {
	if u != nil {
		cic.SetUpdatedAt(*u)
	}
	return cic
}

// SetDeletedAt sets the "deleted_at" field.
func (cic *CoinInfoCreate) SetDeletedAt(u uint32) *CoinInfoCreate {
	cic.mutation.SetDeletedAt(u)
	return cic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableDeletedAt(u *uint32) *CoinInfoCreate {
	if u != nil {
		cic.SetDeletedAt(*u)
	}
	return cic
}

// SetID sets the "id" field.
func (cic *CoinInfoCreate) SetID(u uuid.UUID) *CoinInfoCreate {
	cic.mutation.SetID(u)
	return cic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableID(u *uuid.UUID) *CoinInfoCreate {
	if u != nil {
		cic.SetID(*u)
	}
	return cic
}

// Mutation returns the CoinInfoMutation object of the builder.
func (cic *CoinInfoCreate) Mutation() *CoinInfoMutation {
	return cic.mutation
}

// Save creates the CoinInfo in the database.
func (cic *CoinInfoCreate) Save(ctx context.Context) (*CoinInfo, error) {
	var (
		err  error
		node *CoinInfo
	)
	cic.defaults()
	if len(cic.hooks) == 0 {
		if err = cic.check(); err != nil {
			return nil, err
		}
		node, err = cic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cic.check(); err != nil {
				return nil, err
			}
			cic.mutation = mutation
			if node, err = cic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cic.hooks) - 1; i >= 0; i-- {
			if cic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cic *CoinInfoCreate) SaveX(ctx context.Context) *CoinInfo {
	v, err := cic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cic *CoinInfoCreate) Exec(ctx context.Context) error {
	_, err := cic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cic *CoinInfoCreate) ExecX(ctx context.Context) {
	if err := cic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cic *CoinInfoCreate) defaults() {
	if _, ok := cic.mutation.Unit(); !ok {
		v := coininfo.DefaultUnit
		cic.mutation.SetUnit(v)
	}
	if _, ok := cic.mutation.ReservedAmount(); !ok {
		v := coininfo.DefaultReservedAmount
		cic.mutation.SetReservedAmount(v)
	}
	if _, ok := cic.mutation.PreSale(); !ok {
		v := coininfo.DefaultPreSale
		cic.mutation.SetPreSale(v)
	}
	if _, ok := cic.mutation.Logo(); !ok {
		v := coininfo.DefaultLogo
		cic.mutation.SetLogo(v)
	}
	if _, ok := cic.mutation.Env(); !ok {
		v := coininfo.DefaultEnv
		cic.mutation.SetEnv(v)
	}
	if _, ok := cic.mutation.ForPay(); !ok {
		v := coininfo.DefaultForPay
		cic.mutation.SetForPay(v)
	}
	if _, ok := cic.mutation.HomePage(); !ok {
		v := coininfo.DefaultHomePage
		cic.mutation.SetHomePage(v)
	}
	if _, ok := cic.mutation.Specs(); !ok {
		v := coininfo.DefaultSpecs
		cic.mutation.SetSpecs(v)
	}
	if _, ok := cic.mutation.CreatedAt(); !ok {
		v := coininfo.DefaultCreatedAt()
		cic.mutation.SetCreatedAt(v)
	}
	if _, ok := cic.mutation.UpdatedAt(); !ok {
		v := coininfo.DefaultUpdatedAt()
		cic.mutation.SetUpdatedAt(v)
	}
	if _, ok := cic.mutation.DeletedAt(); !ok {
		v := coininfo.DefaultDeletedAt()
		cic.mutation.SetDeletedAt(v)
	}
	if _, ok := cic.mutation.ID(); !ok {
		v := coininfo.DefaultID()
		cic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cic *CoinInfoCreate) check() error {
	if _, ok := cic.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CoinInfo.name"`)}
	}
	if v, ok := cic.mutation.Name(); ok {
		if err := coininfo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CoinInfo.name": %w`, err)}
		}
	}
	if _, ok := cic.mutation.Unit(); !ok {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required field "CoinInfo.unit"`)}
	}
	if v, ok := cic.mutation.Unit(); ok {
		if err := coininfo.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "CoinInfo.unit": %w`, err)}
		}
	}
	if _, ok := cic.mutation.ReservedAmount(); !ok {
		return &ValidationError{Name: "reserved_amount", err: errors.New(`ent: missing required field "CoinInfo.reserved_amount"`)}
	}
	if _, ok := cic.mutation.PreSale(); !ok {
		return &ValidationError{Name: "pre_sale", err: errors.New(`ent: missing required field "CoinInfo.pre_sale"`)}
	}
	if _, ok := cic.mutation.Logo(); !ok {
		return &ValidationError{Name: "logo", err: errors.New(`ent: missing required field "CoinInfo.logo"`)}
	}
	if _, ok := cic.mutation.Env(); !ok {
		return &ValidationError{Name: "env", err: errors.New(`ent: missing required field "CoinInfo.env"`)}
	}
	if _, ok := cic.mutation.ForPay(); !ok {
		return &ValidationError{Name: "for_pay", err: errors.New(`ent: missing required field "CoinInfo.for_pay"`)}
	}
	if _, ok := cic.mutation.HomePage(); !ok {
		return &ValidationError{Name: "home_page", err: errors.New(`ent: missing required field "CoinInfo.home_page"`)}
	}
	if _, ok := cic.mutation.Specs(); !ok {
		return &ValidationError{Name: "specs", err: errors.New(`ent: missing required field "CoinInfo.specs"`)}
	}
	if _, ok := cic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CoinInfo.created_at"`)}
	}
	if _, ok := cic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CoinInfo.updated_at"`)}
	}
	if _, ok := cic.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "CoinInfo.deleted_at"`)}
	}
	return nil
}

func (cic *CoinInfoCreate) sqlSave(ctx context.Context) (*CoinInfo, error) {
	_node, _spec := cic.createSpec()
	if err := sqlgraph.CreateNode(ctx, cic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (cic *CoinInfoCreate) createSpec() (*CoinInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &CoinInfo{config: cic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: coininfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coininfo.FieldID,
			},
		}
	)
	_spec.OnConflict = cic.conflict
	if id, ok := cic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cic.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldName,
		})
		_node.Name = value
	}
	if value, ok := cic.mutation.Unit(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldUnit,
		})
		_node.Unit = value
	}
	if value, ok := cic.mutation.ReservedAmount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: coininfo.FieldReservedAmount,
		})
		_node.ReservedAmount = value
	}
	if value, ok := cic.mutation.PreSale(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: coininfo.FieldPreSale,
		})
		_node.PreSale = value
	}
	if value, ok := cic.mutation.Logo(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldLogo,
		})
		_node.Logo = value
	}
	if value, ok := cic.mutation.Env(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldEnv,
		})
		_node.Env = value
	}
	if value, ok := cic.mutation.ForPay(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: coininfo.FieldForPay,
		})
		_node.ForPay = value
	}
	if value, ok := cic.mutation.HomePage(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldHomePage,
		})
		_node.HomePage = value
	}
	if value, ok := cic.mutation.Specs(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldSpecs,
		})
		_node.Specs = value
	}
	if value, ok := cic.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coininfo.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cic.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coininfo.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := cic.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coininfo.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinInfo.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinInfoUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
//
func (cic *CoinInfoCreate) OnConflict(opts ...sql.ConflictOption) *CoinInfoUpsertOne {
	cic.conflict = opts
	return &CoinInfoUpsertOne{
		create: cic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cic *CoinInfoCreate) OnConflictColumns(columns ...string) *CoinInfoUpsertOne {
	cic.conflict = append(cic.conflict, sql.ConflictColumns(columns...))
	return &CoinInfoUpsertOne{
		create: cic,
	}
}

type (
	// CoinInfoUpsertOne is the builder for "upsert"-ing
	//  one CoinInfo node.
	CoinInfoUpsertOne struct {
		create *CoinInfoCreate
	}

	// CoinInfoUpsert is the "OnConflict" setter.
	CoinInfoUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *CoinInfoUpsert) SetName(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateName() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldName)
	return u
}

// SetUnit sets the "unit" field.
func (u *CoinInfoUpsert) SetUnit(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldUnit, v)
	return u
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateUnit() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldUnit)
	return u
}

// SetReservedAmount sets the "reserved_amount" field.
func (u *CoinInfoUpsert) SetReservedAmount(v uint64) *CoinInfoUpsert {
	u.Set(coininfo.FieldReservedAmount, v)
	return u
}

// UpdateReservedAmount sets the "reserved_amount" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateReservedAmount() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldReservedAmount)
	return u
}

// AddReservedAmount adds v to the "reserved_amount" field.
func (u *CoinInfoUpsert) AddReservedAmount(v uint64) *CoinInfoUpsert {
	u.Add(coininfo.FieldReservedAmount, v)
	return u
}

// SetPreSale sets the "pre_sale" field.
func (u *CoinInfoUpsert) SetPreSale(v bool) *CoinInfoUpsert {
	u.Set(coininfo.FieldPreSale, v)
	return u
}

// UpdatePreSale sets the "pre_sale" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdatePreSale() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldPreSale)
	return u
}

// SetLogo sets the "logo" field.
func (u *CoinInfoUpsert) SetLogo(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldLogo, v)
	return u
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateLogo() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldLogo)
	return u
}

// SetEnv sets the "env" field.
func (u *CoinInfoUpsert) SetEnv(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldEnv, v)
	return u
}

// UpdateEnv sets the "env" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateEnv() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldEnv)
	return u
}

// SetForPay sets the "for_pay" field.
func (u *CoinInfoUpsert) SetForPay(v bool) *CoinInfoUpsert {
	u.Set(coininfo.FieldForPay, v)
	return u
}

// UpdateForPay sets the "for_pay" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateForPay() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldForPay)
	return u
}

// SetHomePage sets the "home_page" field.
func (u *CoinInfoUpsert) SetHomePage(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldHomePage, v)
	return u
}

// UpdateHomePage sets the "home_page" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateHomePage() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldHomePage)
	return u
}

// SetSpecs sets the "specs" field.
func (u *CoinInfoUpsert) SetSpecs(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldSpecs, v)
	return u
}

// UpdateSpecs sets the "specs" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateSpecs() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldSpecs)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinInfoUpsert) SetCreatedAt(v uint32) *CoinInfoUpsert {
	u.Set(coininfo.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateCreatedAt() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinInfoUpsert) AddCreatedAt(v uint32) *CoinInfoUpsert {
	u.Add(coininfo.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinInfoUpsert) SetUpdatedAt(v uint32) *CoinInfoUpsert {
	u.Set(coininfo.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateUpdatedAt() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinInfoUpsert) AddUpdatedAt(v uint32) *CoinInfoUpsert {
	u.Add(coininfo.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinInfoUpsert) SetDeletedAt(v uint32) *CoinInfoUpsert {
	u.Set(coininfo.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateDeletedAt() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinInfoUpsert) AddDeletedAt(v uint32) *CoinInfoUpsert {
	u.Add(coininfo.FieldDeletedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coininfo.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinInfoUpsertOne) UpdateNewValues() *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coininfo.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.CoinInfo.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CoinInfoUpsertOne) Ignore() *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinInfoUpsertOne) DoNothing() *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinInfoCreate.OnConflict
// documentation for more info.
func (u *CoinInfoUpsertOne) Update(set func(*CoinInfoUpsert)) *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CoinInfoUpsertOne) SetName(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateName() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateName()
	})
}

// SetUnit sets the "unit" field.
func (u *CoinInfoUpsertOne) SetUnit(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateUnit() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateUnit()
	})
}

// SetReservedAmount sets the "reserved_amount" field.
func (u *CoinInfoUpsertOne) SetReservedAmount(v uint64) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetReservedAmount(v)
	})
}

// AddReservedAmount adds v to the "reserved_amount" field.
func (u *CoinInfoUpsertOne) AddReservedAmount(v uint64) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddReservedAmount(v)
	})
}

// UpdateReservedAmount sets the "reserved_amount" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateReservedAmount() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateReservedAmount()
	})
}

// SetPreSale sets the "pre_sale" field.
func (u *CoinInfoUpsertOne) SetPreSale(v bool) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetPreSale(v)
	})
}

// UpdatePreSale sets the "pre_sale" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdatePreSale() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdatePreSale()
	})
}

// SetLogo sets the "logo" field.
func (u *CoinInfoUpsertOne) SetLogo(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetLogo(v)
	})
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateLogo() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateLogo()
	})
}

// SetEnv sets the "env" field.
func (u *CoinInfoUpsertOne) SetEnv(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetEnv(v)
	})
}

// UpdateEnv sets the "env" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateEnv() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateEnv()
	})
}

// SetForPay sets the "for_pay" field.
func (u *CoinInfoUpsertOne) SetForPay(v bool) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetForPay(v)
	})
}

// UpdateForPay sets the "for_pay" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateForPay() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateForPay()
	})
}

// SetHomePage sets the "home_page" field.
func (u *CoinInfoUpsertOne) SetHomePage(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetHomePage(v)
	})
}

// UpdateHomePage sets the "home_page" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateHomePage() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateHomePage()
	})
}

// SetSpecs sets the "specs" field.
func (u *CoinInfoUpsertOne) SetSpecs(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetSpecs(v)
	})
}

// UpdateSpecs sets the "specs" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateSpecs() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateSpecs()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinInfoUpsertOne) SetCreatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinInfoUpsertOne) AddCreatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateCreatedAt() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinInfoUpsertOne) SetUpdatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinInfoUpsertOne) AddUpdatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateUpdatedAt() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinInfoUpsertOne) SetDeletedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinInfoUpsertOne) AddDeletedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateDeletedAt() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateDeletedAt()
	})
}

// Exec executes the query.
func (u *CoinInfoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinInfoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinInfoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoinInfoUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CoinInfoUpsertOne.ID is not supported by MySQL driver. Use CoinInfoUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoinInfoUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoinInfoCreateBulk is the builder for creating many CoinInfo entities in bulk.
type CoinInfoCreateBulk struct {
	config
	builders []*CoinInfoCreate
	conflict []sql.ConflictOption
}

// Save creates the CoinInfo entities in the database.
func (cicb *CoinInfoCreateBulk) Save(ctx context.Context) ([]*CoinInfo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cicb.builders))
	nodes := make([]*CoinInfo, len(cicb.builders))
	mutators := make([]Mutator, len(cicb.builders))
	for i := range cicb.builders {
		func(i int, root context.Context) {
			builder := cicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoinInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cicb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cicb *CoinInfoCreateBulk) SaveX(ctx context.Context) []*CoinInfo {
	v, err := cicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cicb *CoinInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := cicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cicb *CoinInfoCreateBulk) ExecX(ctx context.Context) {
	if err := cicb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinInfo.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinInfoUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
//
func (cicb *CoinInfoCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoinInfoUpsertBulk {
	cicb.conflict = opts
	return &CoinInfoUpsertBulk{
		create: cicb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cicb *CoinInfoCreateBulk) OnConflictColumns(columns ...string) *CoinInfoUpsertBulk {
	cicb.conflict = append(cicb.conflict, sql.ConflictColumns(columns...))
	return &CoinInfoUpsertBulk{
		create: cicb,
	}
}

// CoinInfoUpsertBulk is the builder for "upsert"-ing
// a bulk of CoinInfo nodes.
type CoinInfoUpsertBulk struct {
	create *CoinInfoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coininfo.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinInfoUpsertBulk) UpdateNewValues() *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coininfo.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CoinInfoUpsertBulk) Ignore() *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinInfoUpsertBulk) DoNothing() *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinInfoCreateBulk.OnConflict
// documentation for more info.
func (u *CoinInfoUpsertBulk) Update(set func(*CoinInfoUpsert)) *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CoinInfoUpsertBulk) SetName(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateName() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateName()
	})
}

// SetUnit sets the "unit" field.
func (u *CoinInfoUpsertBulk) SetUnit(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateUnit() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateUnit()
	})
}

// SetReservedAmount sets the "reserved_amount" field.
func (u *CoinInfoUpsertBulk) SetReservedAmount(v uint64) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetReservedAmount(v)
	})
}

// AddReservedAmount adds v to the "reserved_amount" field.
func (u *CoinInfoUpsertBulk) AddReservedAmount(v uint64) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddReservedAmount(v)
	})
}

// UpdateReservedAmount sets the "reserved_amount" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateReservedAmount() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateReservedAmount()
	})
}

// SetPreSale sets the "pre_sale" field.
func (u *CoinInfoUpsertBulk) SetPreSale(v bool) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetPreSale(v)
	})
}

// UpdatePreSale sets the "pre_sale" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdatePreSale() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdatePreSale()
	})
}

// SetLogo sets the "logo" field.
func (u *CoinInfoUpsertBulk) SetLogo(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetLogo(v)
	})
}

// UpdateLogo sets the "logo" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateLogo() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateLogo()
	})
}

// SetEnv sets the "env" field.
func (u *CoinInfoUpsertBulk) SetEnv(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetEnv(v)
	})
}

// UpdateEnv sets the "env" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateEnv() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateEnv()
	})
}

// SetForPay sets the "for_pay" field.
func (u *CoinInfoUpsertBulk) SetForPay(v bool) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetForPay(v)
	})
}

// UpdateForPay sets the "for_pay" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateForPay() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateForPay()
	})
}

// SetHomePage sets the "home_page" field.
func (u *CoinInfoUpsertBulk) SetHomePage(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetHomePage(v)
	})
}

// UpdateHomePage sets the "home_page" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateHomePage() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateHomePage()
	})
}

// SetSpecs sets the "specs" field.
func (u *CoinInfoUpsertBulk) SetSpecs(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetSpecs(v)
	})
}

// UpdateSpecs sets the "specs" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateSpecs() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateSpecs()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinInfoUpsertBulk) SetCreatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinInfoUpsertBulk) AddCreatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateCreatedAt() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinInfoUpsertBulk) SetUpdatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinInfoUpsertBulk) AddUpdatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateUpdatedAt() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinInfoUpsertBulk) SetDeletedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinInfoUpsertBulk) AddDeletedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateDeletedAt() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateDeletedAt()
	})
}

// Exec executes the query.
func (u *CoinInfoUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoinInfoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinInfoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinInfoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
