// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/sphinx-coininfo/pkg/db/ent/description"
	"github.com/NpoolPlatform/sphinx-coininfo/pkg/types"
	"github.com/google/uuid"
)

// Description is the model entity for the Description schema.
type Description struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CoinID holds the value of the "coin_id" field.
	CoinID uuid.UUID `json:"coin_id,omitempty"`
	// HumanReadableName holds the value of the "human_readable_name" field.
	HumanReadableName string `json:"human_readable_name,omitempty"`
	// Descriptions holds the value of the "descriptions" field.
	Descriptions []types.CoinDescription `json:"descriptions,omitempty"`
	// SpecTitle holds the value of the "spec_title" field.
	SpecTitle string `json:"spec_title,omitempty"`
	// Specs holds the value of the "specs" field.
	Specs []types.CoinSpec `json:"specs,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Description) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case description.FieldDescriptions, description.FieldSpecs:
			values[i] = new([]byte)
		case description.FieldCreatedAt, description.FieldUpdatedAt, description.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case description.FieldHumanReadableName, description.FieldSpecTitle:
			values[i] = new(sql.NullString)
		case description.FieldID, description.FieldCoinID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Description", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Description fields.
func (d *Description) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case description.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				d.ID = *value
			}
		case description.FieldCoinID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coin_id", values[i])
			} else if value != nil {
				d.CoinID = *value
			}
		case description.FieldHumanReadableName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field human_readable_name", values[i])
			} else if value.Valid {
				d.HumanReadableName = value.String
			}
		case description.FieldDescriptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field descriptions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &d.Descriptions); err != nil {
					return fmt.Errorf("unmarshal field descriptions: %w", err)
				}
			}
		case description.FieldSpecTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spec_title", values[i])
			} else if value.Valid {
				d.SpecTitle = value.String
			}
		case description.FieldSpecs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field specs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &d.Specs); err != nil {
					return fmt.Errorf("unmarshal field specs: %w", err)
				}
			}
		case description.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				d.CreatedAt = uint32(value.Int64)
			}
		case description.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				d.UpdatedAt = uint32(value.Int64)
			}
		case description.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				d.DeletedAt = uint32(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Description.
// Note that you need to call Description.Unwrap() before calling this method if this Description
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Description) Update() *DescriptionUpdateOne {
	return (&DescriptionClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Description entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Description) Unwrap() *Description {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Description is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Description) String() string {
	var builder strings.Builder
	builder.WriteString("Description(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", coin_id=")
	builder.WriteString(fmt.Sprintf("%v", d.CoinID))
	builder.WriteString(", human_readable_name=")
	builder.WriteString(d.HumanReadableName)
	builder.WriteString(", descriptions=")
	builder.WriteString(fmt.Sprintf("%v", d.Descriptions))
	builder.WriteString(", spec_title=")
	builder.WriteString(d.SpecTitle)
	builder.WriteString(", specs=")
	builder.WriteString(fmt.Sprintf("%v", d.Specs))
	builder.WriteString(", created_at=")
	builder.WriteString(fmt.Sprintf("%v", d.CreatedAt))
	builder.WriteString(", updated_at=")
	builder.WriteString(fmt.Sprintf("%v", d.UpdatedAt))
	builder.WriteString(", deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", d.DeletedAt))
	builder.WriteByte(')')
	return builder.String()
}

// Descriptions is a parsable slice of Description.
type Descriptions []*Description

func (d Descriptions) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
