// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/NpoolPlatform/sphinx-coininfo/pkg/db/ent/coininfo"
	"github.com/NpoolPlatform/sphinx-coininfo/pkg/db/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	coininfoFields := schema.CoinInfo{}.Fields()
	_ = coininfoFields
	// coininfoDescName is the schema descriptor for name field.
	coininfoDescName := coininfoFields[1].Descriptor()
	// coininfo.NameValidator is a validator for the "name" field. It is called by the builders before save.
	coininfo.NameValidator = coininfoDescName.Validators[0].(func(string) error)
	// coininfoDescUnit is the schema descriptor for unit field.
	coininfoDescUnit := coininfoFields[2].Descriptor()
	// coininfo.DefaultUnit holds the default value on creation for the unit field.
	coininfo.DefaultUnit = coininfoDescUnit.Default.(string)
	// coininfo.UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	coininfo.UnitValidator = coininfoDescUnit.Validators[0].(func(string) error)
	// coininfoDescReservedAmount is the schema descriptor for reserved_amount field.
	coininfoDescReservedAmount := coininfoFields[3].Descriptor()
	// coininfo.DefaultReservedAmount holds the default value on creation for the reserved_amount field.
	coininfo.DefaultReservedAmount = coininfoDescReservedAmount.Default.(uint64)
	// coininfoDescPreSale is the schema descriptor for pre_sale field.
	coininfoDescPreSale := coininfoFields[4].Descriptor()
	// coininfo.DefaultPreSale holds the default value on creation for the pre_sale field.
	coininfo.DefaultPreSale = coininfoDescPreSale.Default.(bool)
	// coininfoDescLogo is the schema descriptor for logo field.
	coininfoDescLogo := coininfoFields[5].Descriptor()
	// coininfo.DefaultLogo holds the default value on creation for the logo field.
	coininfo.DefaultLogo = coininfoDescLogo.Default.(string)
	// coininfoDescCreatedAt is the schema descriptor for created_at field.
	coininfoDescCreatedAt := coininfoFields[6].Descriptor()
	// coininfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	coininfo.DefaultCreatedAt = coininfoDescCreatedAt.Default.(func() uint32)
	// coininfoDescUpdatedAt is the schema descriptor for updated_at field.
	coininfoDescUpdatedAt := coininfoFields[7].Descriptor()
	// coininfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	coininfo.DefaultUpdatedAt = coininfoDescUpdatedAt.Default.(func() uint32)
	// coininfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	coininfo.UpdateDefaultUpdatedAt = coininfoDescUpdatedAt.UpdateDefault.(func() uint32)
	// coininfoDescDeletedAt is the schema descriptor for deleted_at field.
	coininfoDescDeletedAt := coininfoFields[8].Descriptor()
	// coininfo.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	coininfo.DefaultDeletedAt = coininfoDescDeletedAt.Default.(func() uint32)
	// coininfoDescID is the schema descriptor for id field.
	coininfoDescID := coininfoFields[0].Descriptor()
	// coininfo.DefaultID holds the default value on creation for the id field.
	coininfo.DefaultID = coininfoDescID.Default.(func() uuid.UUID)
}
