// Code generated by entc, DO NOT EDIT.

package description

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the description type in the database.
	Label = "description"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCoinID holds the string denoting the coin_id field in the database.
	FieldCoinID = "coin_id"
	// FieldHumanReadableName holds the string denoting the human_readable_name field in the database.
	FieldHumanReadableName = "human_readable_name"
	// FieldDescriptions holds the string denoting the descriptions field in the database.
	FieldDescriptions = "descriptions"
	// FieldSpecTitle holds the string denoting the spec_title field in the database.
	FieldSpecTitle = "spec_title"
	// FieldSpecs holds the string denoting the specs field in the database.
	FieldSpecs = "specs"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the description in the database.
	Table = "descriptions"
)

// Columns holds all SQL columns for description fields.
var Columns = []string{
	FieldID,
	FieldCoinID,
	FieldHumanReadableName,
	FieldDescriptions,
	FieldSpecTitle,
	FieldSpecs,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
