// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SphinxCoininfoClient is the client API for SphinxCoininfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SphinxCoininfoClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type serviceExampleClient struct {
	cc grpc.ClientConnInterface
}

func NewSphinxCoininfoClient(cc grpc.ClientConnInterface) SphinxCoininfoClient {
	return &serviceExampleClient{cc}
}

func (c *serviceExampleClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/sphinx.coininfo.v1.SphinxCoininfo/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SphinxCoininfoServer is the server API for SphinxCoininfo service.
// All implementations must embed UnimplementedSphinxCoininfoServer
// for forward compatibility
type SphinxCoininfoServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedSphinxCoininfoServer()
}

// UnimplementedSphinxCoininfoServer must be embedded to have forward compatible implementations.
type UnimplementedSphinxCoininfoServer struct{}

func (UnimplementedSphinxCoininfoServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedSphinxCoininfoServer) mustEmbedUnimplementedSphinxCoininfoServer() {}

// UnsafeSphinxCoininfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SphinxCoininfoServer will
// result in compilation errors.
type UnsafeSphinxCoininfoServer interface {
	mustEmbedUnimplementedSphinxCoininfoServer()
}

func RegisterSphinxCoininfoServer(s grpc.ServiceRegistrar, srv SphinxCoininfoServer) {
	s.RegisterService(&SphinxCoininfo_ServiceDesc, srv)
}

func _SphinxCoininfo_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SphinxCoininfoServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sphinx.coininfo.v1.SphinxCoininfo/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SphinxCoininfoServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SphinxCoininfo_ServiceDesc is the grpc.ServiceDesc for SphinxCoininfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SphinxCoininfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sphinx.coininfo.v1.SphinxCoininfo",
	HandlerType: (*SphinxCoininfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _SphinxCoininfo_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/sphinx-coininfo.proto",
}
