// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CoinInfo is the predicate function for coininfo builders.
type CoinInfo func(*sql.Selector)

// Empty is the predicate function for empty builders.
type Empty func(*sql.Selector)
